version: "3.9"

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node api service
  api:
    image: dealership_database
    ports:
      - 3030:3030
    depends_on:
      - mongo_db
    environment:
      - MONGODB_URI=mongodb+srv://eldhozsaji2002:r79xw6tSL0Uu87bV@dealershipsdb.hvuoo55.mongodb.net/?retryWrites=true&w=majority&appName=dealershipsDB

volumes:
  mongo_data: {}
